// This file is auto-generated by scripts/generate-blog-manifest.mjs
// Do not edit manually.

export const blogModuleLoaders = {
  "ai-photo-dump-ideas": {
    "en": () => import("../app/[locale]/(marketing)/blog/ai-photo-dump-ideas/en.mdx"),
    "zh": () => import("../app/[locale]/(marketing)/blog/ai-photo-dump-ideas/zh.mdx"),
  },
  "how-ai-photo-sets-work": {
    "en": () => import("../app/[locale]/(marketing)/blog/how-ai-photo-sets-work/en.mdx"),
    "zh": () => import("../app/[locale]/(marketing)/blog/how-ai-photo-sets-work/zh.mdx"),
  },
  "how-we-handle-your-selfie": {
    "en": () => import("../app/[locale]/(marketing)/blog/how-we-handle-your-selfie/en.mdx"),
    "zh": () => import("../app/[locale]/(marketing)/blog/how-we-handle-your-selfie/zh.mdx"),
  },
  "sceneself-credits-and-plans": {
    "en": () => import("../app/[locale]/(marketing)/blog/sceneself-credits-and-plans/en.mdx"),
    "zh": () => import("../app/[locale]/(marketing)/blog/sceneself-credits-and-plans/zh.mdx"),
  },
  "sceneself-launch-notes": {
    "en": () => import("../app/[locale]/(marketing)/blog/sceneself-launch-notes/en.mdx"),
    "zh": () => import("../app/[locale]/(marketing)/blog/sceneself-launch-notes/zh.mdx"),
  },
} as const;
